openapi: 3.1.0
info:
  title: Task Planning Web Application API
  description: API for managing tasks, users, and monitoring task statuses in the application.
  version: 1.0.0
  contact:
    email: your-email@example.com
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Add a new user
      requestBody:
        description: User object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        description: Task object that needs to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created successfully
        '400':
          description: Invalid input

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      summary: Update a task status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated task status
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [OPEN, PENDING, COMPLETED, CLOSED]
      responses:
        '200':
          description: Task updated successfully
        '400':
          description: Invalid input
        '404':
          description: Task not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [admin, manager, user]
        managerId:
          type: string
    Task:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [OPEN, PENDING, COMPLETED, CLOSED]
        assignedUserId:
          type: string
        createdBy:
          type: string
        createdAt:
          type: string
          format: date-time
